"""empty message

Revision ID: 1680bec088a0
Revises: bc8c945ac21c
Create Date: 2016-06-21 20:03:48.154354

"""

# revision identifiers, used by Alembic.
revision = '1680bec088a0'
down_revision = 'bc8c945ac21c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    ### end Alembic commands ###
