"""empty message

Revision ID: 16863642987a
Revises: ddacf71694b2
Create Date: 2016-05-23 15:32:56.513181

"""

# revision identifiers, used by Alembic.
revision = '16863642987a'
down_revision = 'ddacf71694b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('curr_session_id', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('last_msg_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_user_curr_session_id'), 'user', ['curr_session_id'], unique=False)
    op.create_index(op.f('ix_user_last_msg_date'), 'user', ['last_msg_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_msg_date'), table_name='user')
    op.drop_index(op.f('ix_user_curr_session_id'), table_name='user')
    op.drop_column('user', 'last_msg_date')
    op.drop_column('user', 'curr_session_id')
    ### end Alembic commands ###
