"""empty message

Revision ID: 1bc5d002f9ef
Revises: 87e08f269dc8
Create Date: 2016-06-11 19:49:54.321519

"""

# revision identifiers, used by Alembic.
revision = '1bc5d002f9ef'
down_revision = '87e08f269dc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepoll', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datepoll', 'end_datetime')
    ### end Alembic commands ###
