"""empty message

Revision ID: 2a7e4124cb5e
Revises: b8f277aad1d8
Create Date: 2016-05-18 21:48:59.437408

"""

# revision identifiers, used by Alembic.
revision = '2a7e4124cb5e'
down_revision = 'b8f277aad1d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_uid', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('messenger_uid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_fb_uid'), 'user', ['fb_uid'], unique=True)
    op.create_index(op.f('ix_user_messenger_uid'), 'user', ['messenger_uid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_messenger_uid'), table_name='user')
    op.drop_index(op.f('ix_user_fb_uid'), table_name='user')
    op.drop_column('user', 'messenger_uid')
    op.drop_column('user', 'fb_uid')
    ### end Alembic commands ###
