"""empty message

Revision ID: 4ab230fa694f
Revises: bbf84a7ae06d
Create Date: 2016-05-31 23:11:39.993483

"""

# revision identifiers, used by Alembic.
revision = '4ab230fa694f'
down_revision = 'bbf84a7ae06d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_conv_session', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('location_conv_session', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_date_conv_session'), 'user', ['date_conv_session'], unique=False)
    op.create_index(op.f('ix_user_location_conv_session'), 'user', ['location_conv_session'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_location_conv_session'), table_name='user')
    op.drop_index(op.f('ix_user_date_conv_session'), table_name='user')
    op.drop_column('user', 'location_conv_session')
    op.drop_column('user', 'date_conv_session')
    ### end Alembic commands ###
