"""empty message

Revision ID: 4c6a1d29b601
Revises: 16863642987a
Create Date: 2016-05-24 01:09:09.919400

"""

# revision identifiers, used by Alembic.
revision = '4c6a1d29b601'
down_revision = '16863642987a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('did_onboarding', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_date_created'), 'user', ['date_created'], unique=False)
    op.create_index(op.f('ix_user_did_onboarding'), 'user', ['did_onboarding'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_did_onboarding'), table_name='user')
    op.drop_index(op.f('ix_user_date_created'), table_name='user')
    op.drop_column('user', 'did_onboarding')
    op.drop_column('user', 'date_created')
    ### end Alembic commands ###
