"""empty message

Revision ID: 5b371dfd21ce
Revises: c12b5656d358
Create Date: 2016-06-28 23:15:01.926310

"""

# revision identifiers, used by Alembic.
revision = '5b371dfd21ce'
down_revision = 'c12b5656d358'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_adding_event_name', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_is_adding_event_name'), 'user', ['is_adding_event_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_adding_event_name'), table_name='user')
    op.drop_column('user', 'is_adding_event_name')
    ### end Alembic commands ###
