"""empty message

Revision ID: 69c10dca798e
Revises: cd7f0b97dfd0
Create Date: 2016-05-30 17:53:11.103910

"""

# revision identifiers, used by Alembic.
revision = '69c10dca798e'
down_revision = 'cd7f0b97dfd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_hash')
    ### end Alembic commands ###
