"""empty message

Revision ID: 7f6a2be96c31
Revises: 1bc5d002f9ef
Create Date: 2016-06-11 19:51:42.652619

"""

# revision identifiers, used by Alembic.
revision = '7f6a2be96c31'
down_revision = '1bc5d002f9ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datepoll', sa.Column('poll_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datepoll', 'poll_number')
    ### end Alembic commands ###
