"""empty message

Revision ID: 87e08f269dc8
Revises: cb25c2c8f46a
Create Date: 2016-06-11 17:44:26.831523

"""

# revision identifiers, used by Alembic.
revision = '87e08f269dc8'
down_revision = 'cb25c2c8f46a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_adding_time', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_removing_time', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_setting_time', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_is_adding_time'), 'user', ['is_adding_time'], unique=False)
    op.create_index(op.f('ix_user_is_removing_time'), 'user', ['is_removing_time'], unique=False)
    op.create_index(op.f('ix_user_is_setting_time'), 'user', ['is_setting_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_setting_time'), table_name='user')
    op.drop_index(op.f('ix_user_is_removing_time'), table_name='user')
    op.drop_index(op.f('ix_user_is_adding_time'), table_name='user')
    op.drop_column('user', 'is_setting_time')
    op.drop_column('user', 'is_removing_time')
    op.drop_column('user', 'is_adding_time')
    ### end Alembic commands ###
