"""empty message

Revision ID: 9180c722343b
Revises: a600c14b7a7e
Create Date: 2016-06-12 18:03:51.267822

"""

# revision identifiers, used by Alembic.
revision = '9180c722343b'
down_revision = 'a600c14b7a7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_msg', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_msg')
    ### end Alembic commands ###
