"""empty message

Revision ID: a600c14b7a7e
Revises: 38cc9fec5f59
Create Date: 2016-06-12 17:26:52.315339

"""

# revision identifiers, used by Alembic.
revision = 'a600c14b7a7e'
down_revision = '38cc9fec5f59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('time', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'time')
    ### end Alembic commands ###
