"""empty message

Revision ID: b8f277aad1d8
Revises: None
Create Date: 2016-05-18 21:43:33.190018

"""

# revision identifiers, used by Alembic.
revision = 'b8f277aad1d8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_uid', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('profile_pic_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fb_user_fb_uid'), 'fb_user', ['fb_uid'], unique=True)
    op.create_index(op.f('ix_fb_user_first_name'), 'fb_user', ['first_name'], unique=True)
    op.create_index(op.f('ix_fb_user_last_name'), 'fb_user', ['last_name'], unique=True)
    op.create_index(op.f('ix_fb_user_profile_pic_id'), 'fb_user', ['profile_pic_id'], unique=True)
    op.create_table('messenger_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messenger_uid', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('profile_pic_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messenger_user_first_name'), 'messenger_user', ['first_name'], unique=True)
    op.create_index(op.f('ix_messenger_user_last_name'), 'messenger_user', ['last_name'], unique=True)
    op.create_index(op.f('ix_messenger_user_messenger_uid'), 'messenger_user', ['messenger_uid'], unique=True)
    op.create_index(op.f('ix_messenger_user_profile_pic_id'), 'messenger_user', ['profile_pic_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=True)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_messenger_user_profile_pic_id'), table_name='messenger_user')
    op.drop_index(op.f('ix_messenger_user_messenger_uid'), table_name='messenger_user')
    op.drop_index(op.f('ix_messenger_user_last_name'), table_name='messenger_user')
    op.drop_index(op.f('ix_messenger_user_first_name'), table_name='messenger_user')
    op.drop_table('messenger_user')
    op.drop_index(op.f('ix_fb_user_profile_pic_id'), table_name='fb_user')
    op.drop_index(op.f('ix_fb_user_last_name'), table_name='fb_user')
    op.drop_index(op.f('ix_fb_user_first_name'), table_name='fb_user')
    op.drop_index(op.f('ix_fb_user_fb_uid'), table_name='fb_user')
    op.drop_table('fb_user')
    ### end Alembic commands ###
