"""empty message

Revision ID: c12b5656d358
Revises: 3cd4474f1c1d
Create Date: 2016-06-28 22:28:26.969369

"""

# revision identifiers, used by Alembic.
revision = 'c12b5656d358'
down_revision = '3cd4474f1c1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_date_used', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_last_date_used'), 'user', ['last_date_used'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_date_used'), table_name='user')
    op.drop_column('user', 'last_date_used')
    ### end Alembic commands ###
