"""empty message

Revision ID: cb25c2c8f46a
Revises: c23cba6a76d8
Create Date: 2016-06-05 19:15:22.998427

"""

# revision identifiers, used by Alembic.
revision = 'cb25c2c8f46a'
down_revision = 'c23cba6a76d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_editing_location', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_is_editing_location'), 'user', ['is_editing_location'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_editing_location'), table_name='user')
    op.drop_column('user', 'is_editing_location')
    ### end Alembic commands ###
