"""empty message

Revision ID: e1401f197944
Revises: 1db5b89981bf
Create Date: 2016-05-20 03:13:26.766586

"""

# revision identifiers, used by Alembic.
revision = 'e1401f197944'
down_revision = '1db5b89981bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_association',
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    schema='main'
    )
    op.drop_table('calendar_event_association')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_association',
    sa.Column('calendar_id', sa.INTEGER(), nullable=True),
    sa.Column('event_id', sa.INTEGER(), nullable=True)
    )
    op.drop_table('calendar_event_association', schema='main')
    ### end Alembic commands ###
